version: '3.8'

services:
  app:
    build: .
    container_name: minitok_api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/minitok
    command: node dist/main.js

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: